-- Task 1: Describe the structure of the `users` table.
-- Task 2: Select `user_id` and `username` from the `users` table.
-- Task 3: Select `username` and `created_at` from the `users` table where `user_id` is 1.
-- Task 4: Select all data from the `users` table.
-- Task 5: Update the `password` field of the `users` table where `user_id` is 1.
-- Task 6: Delete a user from the `users` table where `user_id` is 1.
-- Task 7: Drop the `users` table.
-- Task 8: Select `5 + 2` and display the result.
-- Task 9: Select all columns from `users` where `user_id` is 1.
-- Task 10: Select all columns from `users` where `username` is 'john_doe' and `password` is 'securepassword'.
-- Task 11: Select all columns from `users` where `created_at` is between '2023-01-01' and '2023-12-31'.
-- Task 12: Select all columns from `users` where `username` is in the list ('john_doe', 'jane_doe').
-- Task 13: Select all columns from `users` where `username` matches the pattern 'john%'.
-- Task 14: Select all columns from `users` where `password` is NULL.
-- Task 15: Count the number of rows in the `users` table.
-- Task 16: Select the sum of `age` from the `students` table.
-- Task 17: Select the average of `age` from the `students` table.
-- Task 18: Select the maximum `age` from the `students` table.
-- Task 19: Select the minimum `age` from the `students` table.
-- Task 20: Select `age` and the count of each age from the `students` table grouped by `age`.
